# Generated by Django 5.2.8 on 2025-12-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaccionResena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'reacciones_resenas_canciones',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='LikesResenas',
        ),
    ]
