# Generated by Django 5.2.8 on 2025-11-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=200)),
                ('album', models.CharField(blank=True, max_length=200, null=True)),
                ('genero', models.CharField(max_length=50)),
                ('duracion', models.CharField(default='0:00', max_length=10)),
                ('archivo_audio', models.FileField(blank=True, null=True, upload_to='canciones/')),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Canciones',
            },
        ),
    ]
