# Generated by Django 5.2.8 on 2025-12-02 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaz', '0002_albumes_artistas_canciones_cancionesartistas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
    ]
