# Generated by Django 5.2.8 on 2025-12-14 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaz', '0003_alter_usuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritosAlbumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_favorito', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'favoritos_albumes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FavoritosCanciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_favorito', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'favoritos_canciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('imagen_portada', models.CharField(blank=True, max_length=500, null=True)),
                ('es_publica', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'playlists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlaylistsCanciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'playlists_canciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReaccionResenaCancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'reacciones_resenas_canciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResenaCancion',
            fields=[
                ('resena_cancion_id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_resena', models.DateField(blank=True, null=True)),
                ('puntuacion_estrellas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resenas_canciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DescargasOffline',
            fields=[
                ('descarga_id', models.AutoField(primary_key=True, serialize=False)),
                ('cancion_id', models.IntegerField(blank=True, null=True)),
                ('album_id', models.IntegerField(blank=True, null=True)),
                ('playlist_id', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=20)),
                ('fecha_descarga', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='interfaz.usuario')),
            ],
            options={
                'db_table': 'descargas_offline',
                'unique_together': {('usuario', 'album_id'), ('usuario', 'cancion_id'), ('usuario', 'playlist_id')},
            },
        ),
    ]
