# Generated by Django 5.2.8 on 2025-12-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('userName', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'userlogin',
            },
        ),
    ]
